### ISSUE TITLE
Marks 'passed' tests as 'failed' when they have text in the std:out

### ISSUE THREAD

**Issue by dmanev** [niedbalski/nosetest-xunit-xslt#1]
Marks the following test case as 'failed' but it is 'passed':

<testcase classname="tests.testgen.Base.Analyzer.BaseAnalyzer_test.BaseAnalyzerTest" name="testscan" time="0.935"><system-out><![CDATA[ERR: dat_dou name differs in JIL file definition(DAT_DOUp)
ERR: dat_din name differs in JIL file definition(DAT_DINp)
ERR: dat_ana name differs in JIL file definition(DAT_ANAp)
]]></system-out></testcase>

It is just ouput of the class under test, not an error.

**Comment by niedbalski** [comment]
OK, I adjusted the xslt template for not include messages from passing tests.

Thank you for reporting this.
