### ISSUE TITLE
Could you add screenshots?

### ISSUE THREAD

**Issue by erikbgithub** [niedbalski/nosetest-xunit-xslt#2]
Hi, like maybe other people I just clicked through some websites and then suddenly landed here. I don't have such an XML file at hand, so it would mean some work to look into the XSLT of you. Would you be so nice and add some screenshots to your README? Then it's much easier for someone coming here to see if it's useful for their usecase or not. Thanks!

**Comment by niedbalski** [comment]
I added an screenshot on the README file, hope this fixes your issue :+1: .

Thanks for reporting.

**Comment by erikbgithub** [comment]
Thanks!
